version: '3.8'
services:
  pq:
    image: "postgres"
    container_name: pq
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
  
volumes:
  database-data: 